
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dhion
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        arrozP3 = new javax.swing.JTextField();
        txtCarne = new javax.swing.JTextField();
        txtSalada = new javax.swing.JTextField();
        txtTropeiro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        somaP01 = new javax.swing.JTextField();
        somaP02 = new javax.swing.JTextField();
        somaP03 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtArroz = new javax.swing.JTextField();
        arrozP1 = new javax.swing.JTextField();
        arrozP2 = new javax.swing.JTextField();
        carneP1 = new javax.swing.JTextField();
        carneP2 = new javax.swing.JTextField();
        carneP3 = new javax.swing.JTextField();
        saladaP3 = new javax.swing.JTextField();
        saladaP1 = new javax.swing.JTextField();
        saladaP2 = new javax.swing.JTextField();
        tropeiroP2 = new javax.swing.JTextField();
        tropeiroP3 = new javax.swing.JTextField();
        tropeiroP1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel1.setText("Venda de Jantinhas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 117, 35));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel2.setText("Arroz:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 97, 51, -1));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel3.setText("Carne:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 131, 51, -1));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel4.setText("Salada:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 51, -1));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel5.setText("Tropeiro:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 199, 51, -1));

        arrozP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrozP3ActionPerformed(evt);
            }
        });
        jPanel2.add(arrozP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 70, -1));

        txtCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarneActionPerformed(evt);
            }
        });
        jPanel2.add(txtCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 128, 100, -1));

        txtSalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaladaActionPerformed(evt);
            }
        });
        jPanel2.add(txtSalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 162, 100, -1));

        txtTropeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTropeiroActionPerformed(evt);
            }
        });
        jPanel2.add(txtTropeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 196, 100, -1));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel6.setText("Quantidade Porção:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 120, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gravar.png"))); // NOI18N
        jButton1.setText("Gravar");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 70));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel7.setText("Valor Prato 1");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel8.setText("Valor Prato 2");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel9.setText("Valor Prato 3");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));
        jPanel2.add(somaP01, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 70, -1));
        jPanel2.add(somaP02, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 70, -1));
        jPanel2.add(somaP03, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 70, -1));

        jLabel10.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel10.setText("Prato 3");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 60, -1));

        jLabel11.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel11.setText("Preço:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 66, 45, -1));

        jLabel12.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel12.setText("Prato 1");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, -1));

        jLabel13.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jLabel13.setText("Prato 2");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 60, -1));

        txtArroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArrozActionPerformed(evt);
            }
        });
        jPanel2.add(txtArroz, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 94, 100, -1));

        arrozP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrozP1ActionPerformed(evt);
            }
        });
        jPanel2.add(arrozP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 70, -1));

        arrozP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrozP2ActionPerformed(evt);
            }
        });
        jPanel2.add(arrozP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 70, -1));

        carneP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneP1ActionPerformed(evt);
            }
        });
        jPanel2.add(carneP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 70, -1));

        carneP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneP2ActionPerformed(evt);
            }
        });
        jPanel2.add(carneP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 70, -1));

        carneP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carneP3ActionPerformed(evt);
            }
        });
        jPanel2.add(carneP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 70, -1));

        saladaP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladaP3ActionPerformed(evt);
            }
        });
        jPanel2.add(saladaP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 70, -1));

        saladaP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladaP1ActionPerformed(evt);
            }
        });
        jPanel2.add(saladaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 70, -1));

        saladaP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladaP2ActionPerformed(evt);
            }
        });
        jPanel2.add(saladaP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 70, -1));

        tropeiroP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tropeiroP2ActionPerformed(evt);
            }
        });
        jPanel2.add(tropeiroP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 70, -1));

        tropeiroP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tropeiroP3ActionPerformed(evt);
            }
        });
        jPanel2.add(tropeiroP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 70, -1));

        tropeiroP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tropeiroP1ActionPerformed(evt);
            }
        });
        jPanel2.add(tropeiroP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 70, -1));

        jButton2.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        jButton2.setText("Salvar");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/churrasco.jpg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 390, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrozP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrozP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrozP3ActionPerformed

    private void txtCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarneActionPerformed

    private void txtSaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaladaActionPerformed

    private void txtTropeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTropeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTropeiroActionPerformed

    private void txtArrozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArrozActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArrozActionPerformed

    private void arrozP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrozP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrozP1ActionPerformed

    private void arrozP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrozP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrozP2ActionPerformed

    private void carneP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carneP1ActionPerformed

    private void carneP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carneP2ActionPerformed

    private void carneP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carneP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carneP3ActionPerformed

    private void saladaP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladaP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saladaP3ActionPerformed

    private void saladaP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladaP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saladaP1ActionPerformed

    private void saladaP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladaP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saladaP2ActionPerformed

    private void tropeiroP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tropeiroP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tropeiroP2ActionPerformed

    private void tropeiroP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tropeiroP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tropeiroP3ActionPerformed

    private void tropeiroP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tropeiroP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tropeiroP1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String arrozP01 = arrozP1.getText();
        String carneP01 = carneP1.getText();
        String saladaP01 = saladaP1.getText();
        String tropeiroP01 = tropeiroP1.getText();
        String arrozP02 = arrozP2.getText();
        String carneP02 = carneP2.getText();
        String saladaP02 = saladaP2.getText();
        String tropeiroP02 = tropeiroP2.getText();
        String arrozP03 = arrozP3.getText();
        String carneP03 = carneP3.getText();
        String saladaP03 = saladaP3.getText();
        String tropeiroP03 = tropeiroP3.getText();
        boolean qntValido = false;
        
        if(arrozP1.getText().isEmpty()||arrozP2.getText().isEmpty()||arrozP3.getText().isEmpty()||carneP1.getText().isEmpty()||carneP2.getText().isEmpty()||carneP3.getText().isEmpty()
         ||saladaP1.getText().isEmpty() ||saladaP2.getText().isEmpty()||saladaP3.getText().isEmpty()||tropeiroP1.getText().isEmpty()||tropeiroP2.getText().isEmpty()|| tropeiroP3.getText().isEmpty()       ){
        JOptionPane.showMessageDialog(null, "Obrigatorio informar a quantidade");
        
        }
        else if(txtArroz.getText().isEmpty()||txtCarne.getText().isEmpty()||txtSalada.getText().isEmpty()||txtTropeiro.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Obrigatorio informar os valores");
        
        }
        else{
        if(arrozP1.getText().substring(0).matches("[0-9]*")){
            
            qntValido = true;
       
      matrizP[0][0] = Float.parseFloat(arrozP01);
     }
         if(carneP1.getText().substring(0).matches("[0-9]*")){
          
            qntValido = true;
       
      matrizP[0][1] = Float.parseFloat(carneP01);
     }
          if(saladaP1.getText().substring(0).matches("[0-9]*")){
           
            qntValido = true;
       
      matrizP[0][2] = Float.parseFloat(saladaP01);
     }
       if(tropeiroP1.getText().substring(0).matches("[0-9]*")){
            
            qntValido = true;
       
      matrizP[0][3] = Float.parseFloat(tropeiroP01);
     }
       
       
       if(arrozP2.getText().substring(0).matches("[0-9]*")){
           
            qntValido = true;
       
      matrizP[1][0] = Float.parseFloat(arrozP02);
     }
         if(carneP2.getText().substring(0).matches("[0-9]*")){
            
            qntValido = true;
       
      matrizP[1][1] = Float.parseFloat(carneP02);
     }
          if(saladaP2.getText().substring(0).matches("[0-9]*")){
            
            qntValido = true;
       
      matrizP[1][2] = Float.parseFloat(saladaP02);
     }
       if(tropeiroP2.getText().substring(0).matches("[0-9]*")){
           
            qntValido = true;
       
      matrizP[1][3] = Float.parseFloat(tropeiroP02);
     }
       
       if(arrozP3.getText().substring(0).matches("[0-9]*")){
            
            qntValido = true;
       
      matrizP[2][0] = Float.parseFloat(arrozP03);
     }
         if(carneP3.getText().substring(0).matches("[0-9]*")){
            
            qntValido = true;
       
      matrizP[2][1] = Float.parseFloat(carneP03);
     }
          if(saladaP3.getText().substring(0).matches("[0-9]*")){
         
            qntValido = true;
       
      matrizP[2][2] = Float.parseFloat(saladaP03);
     }
       if(tropeiroP3.getText().substring(0).matches("[0-9]*")){
           if(tropeiroP3.getText().isEmpty()){
           
           }
          
            matrizP[2][3] = Float.parseFloat(tropeiroP03);
           
     }
       
      if(!qntValido){
       JOptionPane.showMessageDialog(null, "Informe uma quantidade valida");
       qntValido = false;
      }
       
       
       
       
       
       float somaP1=0;
       float somaP2=0;
       float somaP3=0;
       
       for(int i =0; i<matrizP.length;i++){
           for(int j = 0; j<matrizP[0].length;j++){
           if(i==0){
           somaP1=somaP1+matrizP[i][j] * matrizC[0][j];
           }
           if(i==1){
           somaP2=somaP2+matrizP[i][j] * matrizC[0][j];
           }
            if(i==2){
           somaP3=somaP3+matrizP[i][j] * matrizC[0][j];
           }
           
           }
       
       }
       
       somaP01.setText("R$ "+Float.toString(somaP1));
       somaP02.setText("R$ "+Float.toString(somaP2));
       somaP03.setText("R$ "+Float.toString(somaP3));}
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public float [][] matrizC;
    public float [][] matrizP;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        matrizC = new float [1][4];
        matrizP = new float [3][4];
        String arroz = txtArroz.getText();
        String carne = txtCarne.getText();
        String salada = txtSalada.getText();
        String tropeiro = txtTropeiro.getText();
        
        if(txtArroz.getText().isEmpty()||txtCarne.getText().isEmpty()||txtSalada.getText().isEmpty()||txtTropeiro.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Obrigatorio informar os valores");
        
        } else{
        
        if(txtArroz.getText().substring(0).matches("[0-9-.]*")){
           
            
        int tamanhoArroz = arroz.length();
        String teste = txtArroz.getText().substring(tamanhoArroz-1);
        String teste2 = txtArroz.getText().substring(0,1);
        if(teste.equals(".")){
           arroz = arroz+"0";
          
           teste = "";
    }
        if(teste2.equals(".")){
           arroz = "0"+arroz;
          
           teste2 ="";
    }
        matrizC[0][0] = Float.parseFloat(arroz);
            
    }
        if(txtCarne.getText().substring(0).matches("[0-9-.]*")){
           
            
        int tamanhoCarne = carne.length();
        String testeCarne = txtCarne.getText().substring(tamanhoCarne-1);
        String testeCarne2 = txtCarne.getText().substring(0,1);
        if(testeCarne.equals(".")){
           carne = carne+"0";
          
           testeCarne = "";
    }
        if(testeCarne2.equals(".")){
           carne = "0"+carne;
          
           testeCarne2 ="";
    }
        matrizC[0][1] = Float.parseFloat(carne);
     }
        
     if(txtSalada.getText().substring(0).matches("[0-9-.]*")){
         
            
        int tamanhoSalada = salada.length();
           String testeSalada = txtSalada.getText().substring(tamanhoSalada-1);
           String testeSalada2 = txtSalada.getText().substring(0,1);
        if(testeSalada.equals(".")){
           salada = salada+"0";
          
           testeSalada = "";
    }
        if(testeSalada2.equals(".")){
           salada = "0"+salada;
         
           testeSalada2 ="";
    }
      matrizC[0][2] = Float.parseFloat(salada);
     }
     
     if(txtTropeiro.getText().substring(0).matches("[0-9-.]*")){
            
            
        int tamanhoTropeiro = tropeiro.length();
           String testeTropeiro = txtTropeiro.getText().substring(tamanhoTropeiro-1);
           String testeTropeiro2 = txtTropeiro.getText().substring(0,1);
        if(testeTropeiro.equals(".")){
           tropeiro = tropeiro+"0";
         
           testeTropeiro = "";
    }
        if(testeTropeiro2.equals(".")){
           tropeiro = "0"+tropeiro;
         
           testeTropeiro2 ="";
    }
      matrizC[0][3] = Float.parseFloat(tropeiro);
     }
          else {
        JOptionPane.showMessageDialog(null, "Digite um numero valido");
        }   
      for(int i =0; i<matrizC[0].length;i++){
      
      }   
     
      if(arrozP1.getText().isEmpty()||arrozP2.getText().isEmpty()||arrozP3.getText().isEmpty()||carneP1.getText().isEmpty()||carneP2.getText().isEmpty()||carneP3.getText().isEmpty()
         ||saladaP1.getText().isEmpty() ||saladaP2.getText().isEmpty()||saladaP3.getText().isEmpty()||tropeiroP1.getText().isEmpty()||tropeiroP2.getText().isEmpty()|| tropeiroP3.getText().isEmpty()       ){
         arrozP1.setText("0");
      carneP1.setText("0");
      saladaP1.setText("0");
      tropeiroP1.setText("0");
      arrozP2.setText("0");
      carneP2.setText("0");
      saladaP2.setText("0");
      tropeiroP2.setText("0");
      arrozP3.setText("0");
      carneP3.setText("0");
      saladaP3.setText("0");
      tropeiroP3.setText("0");
        
        }
     
     
      
        }
      
      
      
      
      
      
    
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrozP1;
    private javax.swing.JTextField arrozP2;
    private javax.swing.JTextField arrozP3;
    private javax.swing.JTextField carneP1;
    private javax.swing.JTextField carneP2;
    private javax.swing.JTextField carneP3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField saladaP1;
    private javax.swing.JTextField saladaP2;
    private javax.swing.JTextField saladaP3;
    private javax.swing.JTextField somaP01;
    private javax.swing.JTextField somaP02;
    private javax.swing.JTextField somaP03;
    private javax.swing.JTextField tropeiroP1;
    private javax.swing.JTextField tropeiroP2;
    private javax.swing.JTextField tropeiroP3;
    private javax.swing.JTextField txtArroz;
    private javax.swing.JTextField txtCarne;
    private javax.swing.JTextField txtSalada;
    private javax.swing.JTextField txtTropeiro;
    // End of variables declaration//GEN-END:variables
}
